### ISSUE TITLE
Checksum error for rar files

### ISSUE THREAD

**Issue by shubhamagarwal92** [Maluuba/GeNeVA_datasets#1]
Hi,

Thank you for providing the [dataset](https://www.microsoft.com/en-us/research/project/generative-neural-visual-artist-geneva/#!downloads). However while using unrar for `i-CLEVR.rar`, I got this checksum error. Could you confirm if the files are not corrupt? Also could you provide the number/count of files for all splits.

```
i-CLEVR/images/CLEVR_val_000888_4.png - checksum error
Unexpected end of archive
Total errors: 2
```

Also, would the images for CoDraw be available from [CoDraw](https://github.com/facebookresearch/CoDraw)? I guess you probably follow the same nomenclature?

**Comment by kracwarlock** [comment]
@shubhamagarwal92 Can you try re-downloading? I just downloaded the zip file and was able to extract all data inside `i-CLEVR.rar` successfully.

Yes, we follow the same nomenclature as CoDraw. The `CoDraw_images.rar` file in our download has all the images in case you don't want to generate them.

**Comment by shubhamagarwal92** [comment]
Thanks. Works now. Earlier I didnt have the `CoDraw_images.rar` either! Closing now.
