### ISSUE TITLE
Model Code

### ISSUE THREAD

**Issue by shubhamagarwal92** [Maluuba/GeNeVA_datasets#3]
Hi, 

Thanks for providing the dataset and the scripts. Do you have an estimate of the timeline for the release of model code? 

Could I consider that the starting point for your code was Miyato and Koyama? 

Thanks :)

**Comment by kracwarlock** [comment]
Hi Shubham. We do not have a date of release in mind yet. I can broadly say that it should be within the next 2 months.

Our base architecture was very similar to https://arxiv.org/abs/1802.05637 so that would be a good starting point in my opinion.

**Comment by zmykevin** [comment]
Hi just want to follow up on this issue. Did you guys still plan to launch the code for Geneva-GAN anytime soon? I checked the project page and there is still no update yet. Thanks.

**Comment by kracwarlock** [comment]
The [project page](https://www.microsoft.com/en-us/research/project/generative-neural-visual-artist-geneva/) has now been updated with links to the code.
