### ISSUE TITLE
Do you have the plan to release the Training and Model code?

### ISSUE THREAD

**Issue by luowy1001** [Maluuba/GeNeVA_datasets#4]
Firstly, THANKS for your great work!
Do you have the plan to release the Training and Model code?
THANKS!

**Comment by kracwarlock** [comment]
Thank you for your comment. We plan to release the training code and pre-trained model in ~1 month. Links would be available on the [project page](https://www.microsoft.com/en-us/research/project/generative-neural-visual-artist-geneva/).

**Comment by luowy1001** [comment]
THANKS!
I'm looking forward to it.

**Comment by kracwarlock** [comment]
The [project page](https://www.microsoft.com/en-us/research/project/generative-neural-visual-artist-geneva/) has now been updated with links to the code.
