### ISSUE TITLE
I can't find file "10K_instance_occurence_58_names.txt".

### ISSUE THREAD

**Issue by warutkrub** [Maluuba/GeNeVA_datasets#5]
I can't find file "10K_instance_occurence_58_names.txt". 
The file is mention in config **"codraw_objects_source: 'raw-data/CoDraw/10K_instance_occurence_58_names.txt'".**

**Comment by kracwarlock** [comment]
The file is supposed to extracted in this line: https://github.com/Maluuba/GeNeVA_datasets/blob/7f57c08c390a1de5cf26bb955f3bc3047b721711/scripts/download_data.sh#L55

Did the `scripts/download_data.sh` script fail for you?

**Comment by lihkinVerma** [comment]
This  https://drive.google.com/file/d/0B-u9nH58139bTy1XRFdqaVEzUGs/view needs permission for download. Is there anyone approving it? I just raised the request

**Comment by kracwarlock** [comment]
abstract scenes can also be download from here if that url is failing https://www.microsoft.com/en-us/download/details.aspx?id=52035
