### ISSUE TITLE
download_data.sh Permission Issue

### ISSUE THREAD

**Issue by abyildirim** [Maluuba/GeNeVA_datasets#6]
Hi,

The [download_data.sh](https://github.com/Maluuba/GeNeVA_datasets/blob/master/scripts/download_data.sh) script is throwing an exception because the CoDraw_1_0.json file (line 43) is not open to access, which should be downloadable from the given [Google Drive link](https://drive.google.com/file/d/0B-u9nH58139bTy1XRFdqaVEzUGs/view). Also, the [link](https://vision.ece.vt.edu/clipart/dataset/AbstractScenes_v1.1.zip) provided for the background image is not working (line 54). Can you please check the availability status of these files?

**Comment by lihkinVerma** [comment]
Did anyone approved your request to access this file? I too is facing the same issue. Is there any workaround?

**Comment by abyildirim** [comment]
I found their pre-processed versions in a related repository: [SSCR](https://github.com/tsujuifu/pytorch_sscr). I hope it helps you.

**Comment by lihkinVerma** [comment]
Thankyou @abyildirim It helped a lot.

**Comment by kracwarlock** [comment]
They seem to have moved it here: https://github.com/facebookresearch/CoDraw/releases
